# Generated by Django 2.1.1 on 2018-09-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_bt_id', models.IntegerField(blank=True, default=None, null=True)),
                ('department', models.CharField(choices=[('Inspection', 'Inspection'), ('Engineering', 'Engineering')], default='Engineering', max_length=255)),
                ('project_type', models.CharField(choices=[('Equipment Inspection', 'Equipment Inspection'), ('Engineering Design', 'Engineering Design')], default='Engineering Design', max_length=255)),
                ('province', models.CharField(choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba')], default='Alberta', max_length=255)),
                ('title', models.CharField(default='Inspection of', max_length=255)),
                ('project_number', models.CharField(default='AE218', max_length=255)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('project_terms', models.CharField(choices=[('Lump Sum', 'Lump Sum'), ('Monthly', 'Monthly')], default='Lump Sum', max_length=255)),
                ('purchase_order', models.CharField(default='PO', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Started', 'Not Started'), ('Completed', 'Completed')], default='Active', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to='accounts.Company')),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proejct_client_contact', to='accounts.Person')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='accounts.Company')),
                ('project_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_supervisor', to='accounts.Person')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
    ]
