# Generated by Django 2.1.1 on 2018-09-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='btareaofgovernance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('AttributeCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lstaogtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstcontacttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstcountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstDocumentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstmunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstmunicipalitytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstnameprefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstnamesuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstprofession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstprofessiondesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstprofessionlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
                ('Abbr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskdescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
                ('Abbr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
                ('Abbr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstunittype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('ParentTask', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('ParentTask', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('Level', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('EstHours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ActHours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Comments', models.CharField(max_length=255)),
                ('permission', models.CharField(default='{}', max_length=255)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='website.lsttaskcategory')),
                ('Description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='website.lsttaskdescription')),
                ('Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='website.lsttaskdetail')),
                ('Phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase', to='website.lstPhase')),
                ('RateUnits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateunits', to='website.lstunit')),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resource', to='accounts.Person')),
            ],
        ),
        migrations.AddField(
            model_name='lstunit',
            name='Type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unittype', to='website.lstunittype'),
        ),
    ]
