# Generated by Django 2.0.7 on 2018-08-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_category', models.CharField(default='', max_length=255)),
                ('equipment_subcategory', models.CharField(default='', max_length=255)),
                ('manufacturer', models.CharField(default='', max_length=255)),
                ('serial_number', models.CharField(default='', max_length=255)),
                ('model_number', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
