# Generated by Django 2.0.7 on 2018-08-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Inspection', max_length=255)),
                ('project_type', models.CharField(default='Inspection', max_length=255)),
                ('province', models.CharField(default='Alberta', max_length=255)),
                ('title', models.CharField(default='Inspection of', max_length=255)),
                ('project_number', models.CharField(default='AE218', max_length=255)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('project_terms', models.CharField(default='Lump Sum', max_length=255)),
                ('purchase_order', models.CharField(default='PO', max_length=255)),
                ('status', models.CharField(default='Active', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='accounts.Company')),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contact', to='accounts.Person')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.Company')),
                ('project_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='accounts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='images/')),
                ('inspection_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='inspections.Inspection')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('inspection_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='inspections.Inspection')),
            ],
        ),
    ]
